# Lists, numpy arrays and all those confusing essential things that we do all the time


# Package importing

In [92]:
import numpy as np

np.random.random()   #Random real number uniformly distributed between 0 and 1

0.5319723741227683

In [93]:
np.random.normal()  #Random real number following Gaussian distribution with mean=0 and standard deviation=1

1.2241779246356868

Or you can also import a particular function or a subpackage from a package like this

In [94]:
from numpy import random
random.normal()

0.6605343877252609

In [95]:
#OR:
from numpy.random import normal
normal()

-0.5652052462647814

# Lists in python

Lists are some of the most useful data structures in basic python. You can put anything you want in a list, you can change individual cells, elements can be lists themselves too.

In [96]:
mylist=[1,2,3,'a',True,[5,6]]

In [97]:
print mylist
print mylist[5]

[1, 2, 3, 'a', True, [5, 6]]
[5, 6]


An extremely useful pre-defined function is "range":

In [98]:
print range(5)
print range(4,10)

[0, 1, 2, 3, 4]
[4, 5, 6, 7, 8, 9]


One of the most useful things about lists in python, is that they can be defined recursively, in a very "math" way

In [99]:
listA=range(10)
listB=[2*elem for elem in listA]
print listA
print listB

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [100]:
listC=[(idx,2**elem) for idx,elem in enumerate(listA)]
listD=[2**elem for idx,elem in enumerate(listA) if elem>4]
print listC
print listD

[(0, 1), (1, 2), (2, 4), (3, 8), (4, 16), (5, 32), (6, 64), (7, 128), (8, 256), (9, 512)]
[32, 64, 128, 256, 512]


In [101]:
listE=[('id:'+str(idx),'power:'+str(2**elem)) for idx,elem in enumerate(listA)]
print listE

[('id:0', 'power:1'), ('id:1', 'power:2'), ('id:2', 'power:4'), ('id:3', 'power:8'), ('id:4', 'power:16'), ('id:5', 'power:32'), ('id:6', 'power:64'), ('id:7', 'power:128'), ('id:8', 'power:256'), ('id:9', 'power:512')]


# Numpy array and indexing

You can create a numpy array a couple of different ways. One of them is to use np.arange, the equivalent of range() we saw for lists, but also creates floats

The BEST thing about numpy arrays, is that you can do math on them treating them as single numbers, and it will do the operations to EACH element by default!

In [102]:
print np.arange(10)
print np.arange(5,10)

print np.arange(1.5,4,.5)  #start, end (excluded) and step
print np.arange(3,4,.1)

print 1/np.arange(0,10.5,.5)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[ 1.5  2.   2.5  3.   3.5]
[ 3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9]
[        inf  2.          1.          0.66666667  0.5         0.4
  0.33333333  0.28571429  0.25        0.22222222  0.2         0.18181818
  0.16666667  0.15384615  0.14285714  0.13333333  0.125       0.11764706
  0.11111111  0.10526316  0.1       ]


/Users/riccardo/anaconda/envs/py27/lib/python2.7/site-packages/ipykernel/__main__.py:7: RuntimeWarning: divide by zero encountered in divide


OR we can produce lists and then convert them to numpy arrays in a straightforward way:

In [103]:
print np.array([1,2,3])

print np.array([3**x for x in np.arange(0,4,.5)])    

#THIS CAN BE DONE BETTER WITH THIS:
myarray=3**np.arange(0,4,.5)
print myarray

[1 2 3]
[  1.           1.73205081   3.           5.19615242   9.          15.58845727
  27.          46.7653718 ]
[  1.           1.73205081   3.           5.19615242   9.          15.58845727
  27.          46.7653718 ]


In [104]:
print myarray.shape
print myarray.shape[0]

(8,)
8


Indexing is pretty flexible

In [105]:
print myarray[3:5]  #3 to 5, 5 excluded
print myarray[3:]   #3 onwards
print myarray[:4]    #Until 4, i.e. 0,1,2,3
print myarray[:-2]   #Until two from the end, i.e. exclude the last two

[ 5.19615242  9.        ]
[  5.19615242   9.          15.58845727  27.          46.7653718 ]
[ 1.          1.73205081  3.          5.19615242]
[  1.           1.73205081   3.           5.19615242   9.          15.58845727]


In [106]:
indexing_list=[3,4,5]
print myarray[indexing_list]

[  5.19615242   9.          15.58845727]


In [107]:
print np.ones(4)

boolean_indexing=np.ones_like(myarray)
print boolean_indexing
boolean_indexing[[4,5,6]]=False
print boolean_indexing.astype('bool')

[ 1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.]
[ True  True  True  True False False False  True]


In [108]:
print np.arange(myarray.shape[0])[boolean_indexing.astype('bool')]

[0 1 2 3 7]


In [109]:
print np.ones((3,4))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [110]:
y,x=np.mgrid[:4,:5]
print x


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [111]:
print y

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]


In [112]:
print x**2+y**2

[[ 0  1  4  9 16]
 [ 1  2  5 10 17]
 [ 4  5  8 13 20]
 [ 9 10 13 18 25]]
